"""add domain guardrails table

Revision ID: a1986aa782c2
Revises: 3f9930ea8088
Create Date: 2025-12-06 00:03:11.257837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1986aa782c2'
down_revision: Union[str, Sequence[str], None] = '3f9930ea8088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_guardrails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('rule', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_guardrails_domain'), 'domain_guardrails', ['domain'], unique=True)
    op.create_index(op.f('ix_domain_guardrails_id'), 'domain_guardrails', ['id'], unique=False)
    op.create_index(op.f('ix_domain_guardrails_user_id'), 'domain_guardrails', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_guardrails_user_id'), table_name='domain_guardrails')
    op.drop_index(op.f('ix_domain_guardrails_id'), table_name='domain_guardrails')
    op.drop_index(op.f('ix_domain_guardrails_domain'), table_name='domain_guardrails')
    op.drop_table('domain_guardrails')
    # ### end Alembic commands ###
